apiVersion: v1
kind: Service

metadata:
  name: dummy-app-service
  namespace: dummy

spec:
  selector:
    app: dummy-app

  type: NodePort

  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
